### PR TITLE
Migrate gapi authentication to GSI

### LINKED ISSUE #16: Picker window does not open :  idpiframe_initialization_failed
Screenshot 2022-05-11 at 7 59 40 PM

```
{
   error: "idpiframe_initialization_failed"
   details:"You have created a new client application that uses libraries for user authentication or authorization that will soon be deprecated. New clients must use the new libraries instead; existing clients must also migrate before these libraries are deprecated. See the [Migration Guide](https://developers.google.com/identity/gsi/web/guides/gis-migration) for more information."
}
```

### PR DESCRIPTION
**Pull request by gg-martins091**
Migrating the old and deprecated GAPI way of authenticating to the new GSI lib.

Fixes #16,  #17 and #20 .

### CODE REVIEW

**Comment by mhkasif** [comment]
@gg-martins091  any way i can install the package with your updates?

**Comment by rased24** [comment]
I need this one too

**Comment by ggmartins091** [comment]
If @Jose-cd doesn't respond today I'll publish it through my fork to npm until this gets merged as I don't intend to maintain any project right now.

**Comment by Jose-cd** [comment]
Merged, I'll do some fixes and update the npm package.

**Pull request merged**
