### PR TITLE
Added ability to display root folders only

### PR DESCRIPTION
**Pull request by muhammadsajid1997**
It was not possible in the current package to have root folder for selection i.e. view but it only applied to upload

### CODE REVIEW

**Comment by ndbaba1** [comment]
I was about creating a PR to fix this issue. Hopefully this is merged as soon as possible

**Comment by muhammadsajid1997** [comment]
@Jose-cd Kindly review the PR and merge.
Thanks.

**Comment by ndbaba1** [comment]
@muhammadsajid1997 was there a way you were able to get this working while waiting for this PR to be merged. I meant such that your changes still remains even after this package is re-installed

**Comment by muhammadsajid1997** [comment]
@ndbaba1 I forked this repo, created the changes and PR. Then I published this as a npm package in my github. That way I used.

**Comment by Jose-cd** [comment]
Merged, Thanks.

**Pull request merged**
